### ISSUE TITLE
Request: Harvesting Leaves

### ISSUE THREAD

**Issue by mtnjewk** [Darkhax-Minecraft/BotanyTrees#32]
hello, i've noticed that the hopping botanies only collect wood,sticks,apples and saplings. Is there anyway I can make them collect the tree leaves aswell?

**Comment by Darkhax** [comment]
Hello, not including leaves in the loot pool was an intentional design choice. Many players don't want leaves and it just spams up their storage. These loot pools are completely configurable though and you can add leaves yourself using Data Packs or CraftTweaker. https://github.com/Darkhax-Minecraft/BotanyPots/wiki
