### ISSUE TITLE
Pam's Harvestcraft Trees Compatibility

### ISSUE THREAD

**Issue by lmclarke** [Darkhax-Minecraft/BotanyTrees#49]
Hey there. Everything I can find suggests that Pam's Harvestcraft Trees and this mod should already be compatible in 1.18.2, but the pots don't allow you to use the trees with them. 

UPDATE: I was able to get a version that works with Pam's going in a sort of round-about way. If you go to the curseforge page for Botany Trees, click files, and select the 1.18.2 version from the list, it doesn't support Pam's trees. If you go directly [here](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/3151563) and pick the 1.18.2 version from the sidebar that was updated 3 days ago (as of today), it does support Pam's.

**Comment by Darkhax** [comment]
Hello, thanks for the issue report. CurseForge attempts to display the most stable files on the main page for mods rather than the most up to date files. Authors can not select which files are displayed here. Players are recommended to always check the files tab which has every file and is generally more reliable.
