### ISSUE TITLE
Suggestion - Mod compatibility + Feature request

### ISSUE THREAD

**Issue by xEllierose** [Darkhax-Minecraft/BotanyTrees#52]
I would like to suggest compatibility for some mods
Ancient Saplings with Quark Mod <- I see that this is listed as a compatible mod, but the sapling doesn't work for me.
Cucumber/Rice Seeds with Exlines Sushi Mod
Coconut Seedling with Ecologics Mod

I would additionally like to suggest somehow allowing botany pots to collect the leaves from each tree! I asked for some help in the discord about this, but I was told that this feature is not part of the pots. I would love if it was so I wouldn't have to make an additional regular tree farm. Thank you!

I have both Botany Pots and Trees installed.

**Comment by Darkhax** [comment]
Thanks for letting me know. Looks like ancient sapling is new to Quark and the coconut was missed because it's not a sapling. This should be fixed in 5.0.8 on CurseForge. 

> Cucumber/Rice Seeds with Exlines Sushi Mod

This mod is just trees so this will be fixed on Botany Pots end.

> I would additionally like to suggest somehow allowing botany pots to collect the leaves from each tree!

Leaves were intentionally removed because they created a lot of spam that most users did not want. You can look into making a datapack that will add them back though.
