### ISSUE TITLE
Pam's HC2 Trees : Acorn is missing

### ISSUE THREAD

**Issue by Oddlybird** [Darkhax-Minecraft/BotanyTrees#77]
Looks like pam snuck an extra type of tree in there, so acorns won't grow in the pots yet...  Relevant item ID's:

- pamhc2trees:acorn_sapling
- pamhc2trees:acornitem
- they grow on oaks

**Comment by Darkhax** [comment]
Thanks for letting me know about this. It looks like they actually added several new saplings. This should be fixed in [4.0.13](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/5086356) for MC 1.18.2. I will look into compatibility for 1.20.1 soon if it's not already supported. If the CurseForge link doesn't work give it a few minutes as the file was just uploaded and they need time to process new files.

**Comment by Darkhax** [comment]
This is now fixed in 1.20.1 with [9.0.8](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/5086365).
